/** Real editor workflow with in-memory campaign/row fixtures. Never saves campaign data. */
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium,type Frame} from 'playwright';
const origin=process.argv[2]||'http://localhost:5174';
async function main(){const original=await fs.readFile('campaign/sse-dco-creative.json','utf8'),fixture=JSON.parse(original);fixture.layoutRules=[];fixture.feed.sampleRows=[{...fixture.feed.sampleRows[0],Default:true,offer_count_num:1,tc_type_enum:'tcs_only',tc_terms_text:'Terms apply.\nSee website for details.'}];let payload:any;
 const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1650,height:1100}}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('net::ERR'))errors.push(m.text());});
 await page.route(url=>url.pathname==='/api/creative',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(fixture)}));
 await page.route(url=>url.pathname==='/api/feed-schema',async route=>{const response=await route.fetch(),schema=await response.json();await route.fulfill({json:{...schema,rows:fixture.feed.sampleRows}});});
 await page.route(url=>/\/api\/creative\/[^/]+\/view/.test(url.pathname),route=>{payload=route.request().postDataJSON();return route.continue();});
 await page.goto(origin);const ready=async()=>{await page.waitForTimeout(150);await page.locator('[data-production-frame][data-ready="true"]').waitFor({timeout:45000});};await ready();
 await page.getByLabel('Ad size',{exact:true}).selectOption('300x600');await ready();await page.getByRole('slider',{name:'Timeline scrubber'}).evaluate((el:any)=>{el.value='60';el.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.locator('[data-section="layers"] .sidebar-section-toggle').click();const row=(id:string)=>page.locator(`[data-section="layers"] [data-layer-id="${id}"] .layer-row-main`).first();
 await row('logo-act1').click();await row('terms-solo').click({modifiers:['Meta']});const panel=page.locator('.selected-layout-rules');await panel.locator(':scope > summary').click();await panel.getByRole('button',{name:'Arrange selected items…'}).click();
 const drag=async(locator:any,dx:number,dy:number)=>{const b=await locator.boundingBox();assert.ok(b);await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+dx,b.y+b.height/2+dy,{steps:3});await page.mouse.up();await page.waitForTimeout(80);};
 await panel.getByText('Layout area',{exact:true}).click();await panel.getByLabel('Layout area top').fill('420');await panel.getByLabel('Layout area height').fill('160');const scale=(await page.locator('[data-production-frame]').boundingBox())!.width/300;await drag(page.getByRole('button',{name:'Move layout area',exact:true}),10*scale,10*scale);assert.ok(Math.abs(Number(await panel.getByLabel('Layout area top').inputValue())-430)<.2);await panel.getByLabel('Layout area top').fill('420');await panel.getByRole('button',{name:'Apply layout',exact:true}).click();await ready();
 const frame=async()=>await page.locator('[data-production-frame]').elementHandle().then(h=>h!.contentFrame()) as Frame;
 const diagnostics=async()=>await (await frame()).evaluate(()=>(window as any).__DCO_LAYOUT_DIAGNOSTICS__);
 let results=await diagnostics();assert.ok(results.every((d:any)=>d.status==='active'),JSON.stringify(results));assert.ok(Math.abs(results.find((d:any)=>d.targetId==='logo-act1').targetInk.top-420)<.2);assert.ok(Math.abs(results.find((d:any)=>d.targetId==='terms-solo').targetInk.bottom-580)<.2);
 await page.keyboard.press('Meta+z');await ready();assert.equal((payload.document.layoutRules||[]).length,0);await page.keyboard.press('Meta+Shift+z');await ready();assert.equal(payload.document.layoutRules.length,1);
 const authored=JSON.stringify(payload.document);await panel.getByText('Try different content',{exact:true}).click();await panel.getByLabel('Preview text element').selectOption('terms-solo');await panel.getByRole('button',{name:'Try empty',exact:true}).click();await ready();results=await diagnostics();const logo=results.find((d:any)=>d.targetId==='logo-act1');assert.ok(Math.abs(logo.targetInk.top+logo.targetInk.height/2-500)<.2);assert.equal(JSON.stringify(payload.document),authored);
 await page.screenshot({path:'output/rules/responsive-empty.png'});await panel.getByRole('button',{name:'Restore actual copy',exact:true}).click();await ready();await page.screenshot({path:'output/rules/responsive-with-terms.png'});
 await panel.getByRole('button',{name:'Remove layout',exact:true}).click();await ready();await panel.getByLabel('Conditional placement item').selectOption('logo-act1');await panel.getByLabel('Condition element').selectOption('terms-solo');await panel.getByLabel('Element condition').selectOption('has-text');await panel.getByLabel('Placement top').fill('420');await panel.getByRole('button',{name:'Empty · B',exact:true}).click();await panel.getByLabel('Placement top').fill('490');
 await panel.getByRole('button',{name:'Preview & place on canvas',exact:true}).click();await ready();assert.equal(await (await frame()).locator('#logo-act1').evaluate(e=>getComputedStyle(e).top),'490px');await drag(page.getByRole('button',{name:'Move conditional placement',exact:true}),10*scale,15*scale);await ready();assert.ok(Math.abs(Number(await panel.getByLabel('Placement top').inputValue())-505)<.2);assert.ok(Math.abs(Number(await panel.getByLabel('Placement left').inputValue())-90)<.2);await page.screenshot({path:'output/rules/conditional-editor.png'});await panel.getByRole('button',{name:'End preview',exact:true}).click();await ready();
 await panel.getByRole('button',{name:'Apply rule',exact:true}).click();await ready();results=await diagnostics();assert.equal(results[0].branch,'when');assert.equal(await (await frame()).locator('#logo-act1').evaluate(e=>getComputedStyle(e).top),'420px');
 const content=panel.locator('details').filter({has:page.locator('summary').getByText('Try different content',{exact:true})});await panel.getByText('Try different content',{exact:true}).click();await panel.getByLabel('Preview text element').selectOption('terms-solo');await panel.getByRole('button',{name:'Try empty',exact:true}).click();await ready();results=await diagnostics();assert.equal(results[0].branch,'otherwise');assert.equal(await (await frame()).locator('#logo-act1').evaluate(e=>getComputedStyle(e).top),'505px');await panel.getByRole('button',{name:'Restore actual copy'}).click();await ready();
 assert.equal(await page.getByText('Cross-axis alignment',{exact:true}).count(),0);assert.deepEqual(errors,[]);assert.equal(await fs.readFile('campaign/sse-dco-creative.json','utf8'),original);console.log('PASS multi-selection area, ink edges, empty-text centring, sandboxed content, conditional A/B, canvas preview and restored live condition; campaign unchanged');
 }finally{await browser.close();}}
main().catch(error=>{console.error(error);process.exitCode=1;});
