// Editor-only fixtures; never writes the campaign file.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium,type Frame} from 'playwright';
import {campaignScopes} from '../src/lib/campaign-variants';
import {editOwnershipVersion} from '../src/lib/ownership-ui';
import {responsiveLayoutSource} from '../src/lib/responsive-layout';
const origin=process.argv[2]||'http://localhost:5174';
async function main(){const original=await fs.readFile('campaign/sse-dco-creative.json','utf8');let fixture=JSON.parse(original);fixture.layoutRules=[];fixture.clock.loop=true;const row={...fixture.feed.sampleRows.find((r:any)=>Number(r.offer_count_num)===0),Default:true,offer_count_num:0,tc_type_enum:'tcs_only',include_roundel_frame_bool:true,navy_headlines_bool:true,tc_terms_text:'First legal line\nSecond legal line\nThird legal line\nFourth legal line\nFifth legal line\nSixth legal line'};fixture.feed.sampleRows=[row];fixture=editOwnershipVersion(fixture,'300x600','terms-prices',campaignScopes(fixture,row),'fit',{maxLines:2});
 const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1650,height:1100}}),errors:string[]=[];let payload:any;page.on('pageerror',e=>errors.push(e.message));
 await page.route(url=>url.pathname==='/api/creative',r=>r.fulfill({json:fixture}));await page.route(url=>url.pathname==='/api/feed-schema',async r=>{const response=await r.fetch();await r.fulfill({json:{...await response.json(),rows:[row]}});});await page.route(url=>/\/api\/creative\/[^/]+\/view/.test(url.pathname),r=>{payload=r.request().postDataJSON();return r.continue();});
 await page.goto(origin);const ready=async()=>{await page.waitForTimeout(180);await page.locator('[data-production-frame][data-ready="true"]').waitFor({timeout:45000});};await ready();const frame=async()=>await page.locator('[data-production-frame]').elementHandle().then(h=>h!.contentFrame()) as Frame;
 await page.getByLabel('Ad size',{exact:true}).selectOption('160x600');await ready();await page.locator('[data-section="layers"] .sidebar-section-toggle').click();const layer=(id:string)=>page.locator(`[data-section="layers"] [data-layer-id="${id}"] .layer-row-main`).first();await layer('bluewave').click();
 const inspector=page.getByRole('complementary',{name:'Inspector',exact:true}),y=inspector.getByRole('textbox',{name:'Y',exact:true}),timeline=page.getByRole('slider',{name:'Timeline scrubber'});
 assert.equal(Number(await y.inputValue()),316);const box=await page.locator('[data-production-controls]').boundingBox();assert.ok(box);const scale=box.width/160;await page.mouse.move(box.x+140*scale,box.y+400*scale);await page.mouse.down();await page.mouse.move(box.x+140*scale,box.y+388*scale,{steps:3});await page.mouse.up();await ready();assert.equal(await (await frame()).locator('#bluewave').evaluate(e=>getComputedStyle(e).top),'304px','canvas drag moves the animated artwork');await timeline.focus();await timeline.press('Meta+z');await ready();assert.equal(Number(await y.inputValue()),316);await y.fill('296');await ready();assert.equal(await (await frame()).locator('#bluewave').evaluate(e=>getComputedStyle(e).top),'296px');await y.press('Meta+z');await ready();assert.equal(Number(await y.inputValue()),316,'native field undo');
 await timeline.focus();await y.fill('286');await timeline.focus();await ready();await timeline.press('Meta+z');await ready();assert.equal(Number(await y.inputValue()),316,'one committed field edit');await timeline.press('Meta+Shift+z');await ready();assert.equal(Number(await y.inputValue()),286);
 await y.fill('280');await ready();await page.mouse.move(box.x+140*scale,box.y+400*scale);await page.mouse.down();await page.mouse.move(box.x+140*scale,box.y+388*scale,{steps:3});await page.mouse.up();await ready();assert.equal(Number(await y.inputValue()),268);await timeline.focus();await timeline.press('Meta+z');await ready();assert.equal(Number(await y.inputValue()),280,'drag is separate from focused field edit');await timeline.press('Meta+z');await ready();assert.equal(Number(await y.inputValue()),286);
 const copy=page.locator('[data-feed-field="tc_terms_text"]');await copy.fill('Changed copy');await copy.press('Meta+z');await ready();assert.equal(await copy.inputValue(),row.tc_terms_text);assert.equal(Number(await y.inputValue()),286,'text undo leaves geometry alone');await timeline.focus();
 await page.getByLabel('Ad size',{exact:true}).selectOption('300x600');await ready();await layer('terms-prices').click();
 const inkBottom=async()=>await (await frame()).evaluate(source=>{const e=new Function('return '+source)()(window);return e.ink(document.getElementById('terms-prices')).bottom;},responsiveLayoutSource());const before=await inkBottom();await inspector.getByRole('textbox',{name:'Max lines',exact:true}).fill('6');await ready();assert.ok(Math.abs(await inkBottom()-before)<.3,'max-lines keeps bottom ink fixed');assert.equal(await inspector.getByLabel('Text anchor',{exact:true}).inputValue(),'end');await timeline.focus();
 await page.getByLabel('Ad size',{exact:true}).selectOption('160x600');await ready();await copy.fill('Terms apply.');await timeline.focus();await ready();await layer('logo-act3').click();await layer('terms-prices').click({modifiers:['Meta']});const rules=page.locator('.selected-layout-rules');if(!await rules.getAttribute('open'))await rules.locator(':scope > summary').click();await rules.getByRole('button',{name:'Arrange selected items…',exact:true}).click();await rules.getByText('Layout area',{exact:true}).click();await rules.getByLabel('Layout area top').fill('420');await rules.getByLabel('Layout area height').fill('170');
 await rules.getByText('Animate layout after an exit',{exact:true}).click();await rules.getByLabel('Enable layout transition').check();await rules.getByLabel('Exiting layout item').selectOption('terms-prices');await rules.getByLabel('Layout exit animation').selectOption('terms-prices-fade-offers-0');await rules.getByLabel('Layout return mode').selectOption('hidden');await rules.getByRole('button',{name:'Apply layout',exact:true}).click();await ready();
 assert.equal(payload.document.layoutRules.length,1);const plans=await (await frame()).evaluate(()=>(window as any).__DCO_LAYOUT_TRANSITIONS__);assert.ok(plans.length,'editor production renderer creates exit-linked movement');await page.screenshot({path:'output/rules/motion-editing.png'});
 assert.deepEqual(errors,[]);assert.equal(await fs.readFile('campaign/sse-dco-creative.json','utf8'),original);console.log('PASS motion-owned position, native text/numeric undo, committed-field undo/redo, bottom anchor and exit-transition authoring; campaign unchanged');
 }finally{await browser.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
